# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d55b1cdf7b84122f55b9061dc7ae7d1827a6e6246aa56338abcfb2cf492e50d3746f3f62f2969cc9d9272463c35fb4d0052126a86485edbfa96f7887ed1fde9

test:
  secret_key_base: c99191a6d90b3065fd1b60aea947bcd12f76b9a0d08aeb8ce9a8fe8589f39b43f9d8e018a327e1fb7889dbe30c8d7ac60b687692d5768171ef5bbe231e4288da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
